apiVersion: v1
kind: Service
  labels:
    app: timberio-nodejs
  name: timberio-nodejs-service
  namespace: logging
spec:
  clusterIP: 10.59.244.68
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32127
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: timberio-nodejs
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.192.100.53
